---
- name: Deploy Irods Clients
  hosts: irods-clients
  become: yes
  vars_files:
      - defaults/main.yml
  pre_tasks:

     #change vagrant group, conflicts with slurm
    - name: "Change Centos & Vagrant User Group ID"
      group:
        name: "{{ item.group }}"
        gid: "{{ item.gid }}"
        state: present
      with_items:
        - { gid: 9500, group: centos }
        - { gid: 9600, group: vagrant }

  tasks:

    - name: Install Irods Packages
      yum:
        name:
          - irods-icommands-4.3.0-1.x86_64
          - irods-externals-clang6.0-0-1.0-1.x86_64
        state: latest

    - name: Create Directory For Certifications
      file:
        path: "/etc/irods/ssl"
        state: directory
        owner: "root"
        group: "root"
        mode: '0755'

    - name: Copy Irod Cert
      copy:
        src: "arcirodsprdicat_rs_gsu_edu_cert.cer"
        dest: "/etc/irods/ssl/arcirodsprdicat_rs_gsu_edu_cert.cer"
        owner: "root"
        group: "root"
        mode: '0644'

    - name: Remove Passphrase From Irods Cert
      command: openssl x509 -in /etc/irods/ssl/arcirodsprdicat_rs_gsu_edu_cert.cer -out /etc/irods/ssl/arcirodsprdicat_rs_gsu_edu_cert.pem

#    - debug:
#        var: hostvars[inventory_hostname]
  
