---
- name: Deploy Irods Clients
  hosts: irods-clients
  become: yes
  vars_files:
      - defaults/main.yml
  pre_tasks:

     #change vagrant group, conflicts with slurm
    - name: "Change Centos & Vagrant User Group ID"
      group:
        name: "{{ item.group }}"
        gid: "{{ item.gid }}"
        state: present
      with_items:
        - { gid: 9500, group: centos }
        - { gid: 9600, group: vagrant }

  tasks:

    - import_tasks: tasks/client.yml

  
