---
- name: Deploy Certificate For Irods
  hosts: irod-all
  become: yes
  vars_files:
      - defaults/main.yml
  pre_tasks:

     #change vagrant group, conflicts with slurm
    - name: "Change Centos & Vagrant User Group ID"
      group:
        name: "{{ item.group }}"
        gid: "{{ item.gid }}"
        state: present
      with_items:
        - { gid: 9500, group: centos }
        - { gid: 9600, group: vagrant }

  tasks:

    - name: Create Directory For Certifications
      file:
        path: "/etc/irods/ssl"
        state: directory
        owner: "{{ irods_user }}"
        group: "{{ irods_group }}"
        mode: '0755'

    - name: Copy Irod Cert
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ irods_user }}"
        group: "{{ irods_group }}"
        mode: '0600'
      with_items:
        - { src: 'arcirodsprdicat_rs_gsu_edu_cert.cer', dest: '/etc/irods/ssl/arcirodsprdicat_rs_gsu_edu_cert.cer' }

    - name: Remove Passphrase From Irods Cert
      command: openssl x509 -in /etc/irods/ssl/arcirodsprdicat_rs_gsu_edu_cert.cer -out /etc/irods/ssl/arcirodsprdicat_rs_gsu_edu_cert.pem

#    - debug:
#        var: hostvars[inventory_hostname]
  
